// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleSearch.Persistence;

namespace PeopleSearch.Persistence.Migrations
{
    [DbContext(typeof(PeopleSearchContext))]
    [Migration("20190521004000_PictureUrl")]
    partial class PictureUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeopleSearch.Persistence.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(55);

                    b.Property<int>("PersonId");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PeopleSearch.Persistence.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 15,
                            FirstName = "Peter",
                            Interests = "Physics, Volunteer work, Girls",
                            LastName = "Parker",
                            PictureUrl = "images/peter_parker.png"
                        },
                        new
                        {
                            Id = 2,
                            Age = 40,
                            FirstName = "Tony",
                            Interests = "Mechanical Engineering, Women, Reading",
                            LastName = "Stark",
                            PictureUrl = "images/tony_stark.png"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2000,
                            FirstName = "Thor",
                            Interests = "Honor, Glory, Beer",
                            LastName = "Odinson",
                            PictureUrl = "images/thor_odinson.png"
                        },
                        new
                        {
                            Id = 4,
                            Age = 38,
                            FirstName = "Bruce",
                            Interests = "Anger, Smashing things, Screaming",
                            LastName = "Banner",
                            PictureUrl = "images/bruce_banner.png"
                        },
                        new
                        {
                            Id = 5,
                            Age = 96,
                            FirstName = "Steve",
                            Interests = "Honor, Patriotism, Time travel",
                            LastName = "Rogers",
                            PictureUrl = "images/steve_rogers.png"
                        });
                });

            modelBuilder.Entity("PeopleSearch.Persistence.Entities.Address", b =>
                {
                    b.HasOne("PeopleSearch.Persistence.Entities.Person")
                        .WithOne("Address")
                        .HasForeignKey("PeopleSearch.Persistence.Entities.Address", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
